### ISSUE TITLE
Question on homologous regions

### ISSUE THREAD

**Issue by vladsavelyev** [arshajii/ema-paper-data#1]
Hi,

I ran BWA, LongRanger, and EMA for NA12878 WGS dataset from https://support.10xgenomics.com/genome-exome/datasets/2.1.4/NA12878_WGS_v2, and looking at the challenging regions listed in your notebook:

C4A 6:31965242

![c4a-6-31965242](https://user-images.githubusercontent.com/1575412/37691921-70c11502-2d09-11e8-989c-d8ef1ec71b6d.png)

AMY1 1:104197843

![amy-1-104197843](https://user-images.githubusercontent.com/1575412/37692032-354322da-2d0a-11e8-8e1b-efc740b12c74.png)

CYP2D7 22:42537120

![cyp2d7-22-42537120](https://user-images.githubusercontent.com/1575412/37691987-e6435b0a-2d09-11e8-9db2-9ad5fc44ffb2.png)

It looks like EMA has a higher coverage in those regions, however all those extra alignments are secondary (shaded on the screenshot). I'm wondering if that's an expected picture for EMA? And those secondary alignments could not be resolved via the linked read information? As far as I understand, those secondary alignments will be ignored by variant callers. They look to add up noise in variation, as in this CYP2D6 screenshot (more vertical colored lines at the coverage tracks):

![cyp2d6](https://user-images.githubusercontent.com/1575412/37692372-32cf36fe-2d0c-11e8-918b-cc7cb1e26445.png)

Please, correct me if I'm wrong. I see you evaluated those regions with a more sophisticated strategy by checking against the  NA12878 assemblies, so probably I'm not looking at these regions the right way.

**Comment by arshajii** [comment]
I believe those are actually low-MAPQ alignments (EMA doesn't output separate secondary alignments right now, aside from the `XA` tag which AFAIK doesn't show up in IGV). I was actually planning on refining how MAPQs are assigned to reads in these homologous regions, which should fix this.

**Comment by vladsavelyev** [comment]
That's right, those are primary alignments, sorry for the confusion (though most of them have better matches somewhere else, but I guess we can trust them since you proved they are supported by the assemblies). That's a good news then; looking forward to refined MAPQ.
